modLoader="kotlinforforge"
loaderVersion = "[3,)"
#issueTrackerURL = ""
license='LGPL'

[[mods]]
modId = "malechia"
version = "${version}"
displayName = "Malechia"
authors = "Alexandra"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.malechia]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.malechia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.malechia]]
modId = "architectury"
mandatory = true
versionRange = "[5.7.28,)"
ordering = "AFTER"
side = "BOTH"